package tasystem.entities;

//default package
// Generated Aug 17, 2012 2:41:01 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.JoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.stereotype.Component;


/**
 * Candidate generated by hbm2java
 */

@Component
@Entity
@Table(name="Candidate", uniqueConstraints = {
@UniqueConstraint(columnNames = "email") })
public class Candidate implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="candidateId")
	private Integer candidateId;
	@Column(name = "first_name", nullable = false, length=255)
	private String firstName;
	@Column(name = "last_name", nullable = false, length=255)
	private String lastName;
	@Column(name = "email", nullable = false, length=255)
	private String email;
	@Column(name = "phone_number", nullable = false, length=25)
	private String phoneNumber;
	
		
	@ManyToMany(targetEntity = Requisition.class, cascade = CascadeType.ALL)
	@JoinTable(name = "candidate_requisition", joinColumns = { @JoinColumn(name = "candidateId") }, inverseJoinColumns = { @JoinColumn(name = "req_id") })
	private Set<Requisition> requisitions = new HashSet<Requisition>(0);
	
	@ManyToMany( targetEntity = Recruiter.class, cascade = CascadeType.ALL)
	@JoinTable(name = "candidate_recruiter", joinColumns = { @JoinColumn(name = "candidateId") }, inverseJoinColumns = { @JoinColumn(name = "recId") })
	private  Set<Recruiter> recruiters = new HashSet<Recruiter>(0);
	
	@Column(name = "candidate_rate", unique = false, nullable = false)
	private float candidateRate;
	@Column(name = "times_interviewed", unique = false, nullable = false)
	private int timesInterviewed;
	@Column(name = "times_contacted", unique = false, nullable = false)
	private int timesContacted;

	
	public Candidate() {}


	public Candidate(Integer candidateId, String firstName, String lastName,
			String email, String phoneNumber, Set<Requisition> requisitions,
			Set<Recruiter> recruiters, float candidateRate,
			int timesInterviewed, int timesContacted) {
		super();
		this.candidateId = candidateId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.requisitions = requisitions;
		this.recruiters = recruiters;
		this.candidateRate = candidateRate;
		this.timesInterviewed = timesInterviewed;
		this.timesContacted = timesContacted;
	}


	public Integer getCandidateId() {
		return candidateId;
	}


	public String getFirstName() {
		return firstName;
	}


	public String getLastName() {
		return lastName;
	}


	public String getEmail() {
		return email;
	}


	public String getPhoneNumber() {
		return phoneNumber;
	}


	public Set<Requisition> getRequisitions() {
		return requisitions;
	}


	public Set<Recruiter> getRecruiters() {
		return recruiters;
	}


	public float getCandidateRate() {
		return candidateRate;
	}


	public int getTimesInterviewed() {
		return timesInterviewed;
	}


	public int getTimesContacted() {
		return timesContacted;
	}


	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}


	public void setRequisitions(Set<Requisition> requisitions) {
		this.requisitions = requisitions;
	}


	public void setRecruiters(Set<Recruiter> recruiters) {
		this.recruiters = recruiters;
	}


	public void setCandidateRate(float candidateRate) {
		this.candidateRate = candidateRate;
	}


	public void setTimesInterviewed(int timesInterviewed) {
		this.timesInterviewed = timesInterviewed;
	}


	public void setTimesContacted(int timesContacted) {
		this.timesContacted = timesContacted;
	}

	
	


}
