package tasystem.entities;



import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;


import org.springframework.stereotype.Component;
/**
* Recruiter generated by hbm2java
*/
@Component
@Entity
@Table(name="Recruiter")
public class Recruiter implements java.io.Serializable {

	

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="recId")
	private Integer recId;
	@ManyToMany(targetEntity = Candidate.class, cascade = CascadeType.ALL)
    @JoinTable(name = "candidate_recruiter", joinColumns = { @JoinColumn(name = "rec_id") }, inverseJoinColumns = { @JoinColumn(name = "candidate_id") })
	private Set<Candidate> candidates = new HashSet<Candidate>(0);

	public Recruiter() {
	}

	public Integer getRecId() {
		return this.recId;
	}

	public void setRecId(Integer recId) {
		this.recId = recId;
	}

	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

}

